### ISSUE TITLE
milkviz function dotheatmap fail in SpatialTis when use='dot' using example data

### ISSUE THREAD

**Issue by huiyijiangling** [Mr-Milk/milkviz#17]
milkviz function dotheatmap fail in SpatialTis when use='dot' using example data
![image](https://github.com/Mr-Milk/milkviz/assets/51966240/81b7f1c5-aec9-4da8-b9f0-65929855ef62)

**Comment by Mr-Milk** [comment]
I'm very sorry for the inconvenience. This package and spatialtis is not longer maintained, if you are looking for a nice visualization package for similar features, please see [Marsilea](https://github.com/Marsilea-viz/marsilea), here is a nice tutorial on how to integrate with scanpy, https://scanpy.readthedocs.io/en/stable/how-to/plotting-with-marsilea.html
